name: Test

on: [push, pull_request]

jobs:
  openjdk17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - run: sbt test
